//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public string ID { get; set; }
        public string nameNode { get; set; }
        public string parent { get; set; }
        public string image { get; set; }
        public string port { get; set; }
    }
}
